### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by technohippy** [tc39/proposal-dynamic-code-brand-checks#6]
I'm not sure this is the right place to point this out, but I found a typo in the spec:
https://tc39.es/proposal-dynamic-code-brand-checks/

In "3 Runtime Semantics: PerformEval ( x, callerRealm, strictCaller, direct )" section, "2. If IsCodeLike(x), return x." should be "2. If IsCodeLike(x) is false, return x." or something.

Thanks.

**Comment by mikesamuel** [comment]
Thanks
